# fly.toml app configuration file generated for jingzhuoshop on 2023-09-21T00:32:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jingzhuoshop"
primary_region = "yyz"

[build]
  image = "jingzhuot/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51NsA3yLtPjouTNdVnZqLpBspwxaGNQA4Ctn17bGFE1esfg1p9DYRjev8hzWwSQUwMDST5PnHy42KXJfigMa79VqF00qzs4ynbS"
  Cloudinary__CloudName="dzrkzqqg5"
  Cloudinary__ApiKey="586531294587147"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
